version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
